# Generated by Django 3.1.4 on 2021-04-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcparts', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pcategory',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
