# Generated by Django 3.1.4 on 2021-04-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcparts', '0003_review_pcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desc',
            new_name='review',
        ),
    ]
